/*
 * persistence on watch
*/

enum PersistentKey {
  PERSISTENT_KEY_LIFE_OPPONENT,
  PERSISTENT_KEY_LIFE_PLAYER,
  PERSISTENT_KEY_GAMES_WON_OPPONENT,
  PERSISTENT_KEY_GAMES_WON_PLAYER,
  PERSISTENT_KEY_GAMES_DRAW,
  PERSISTENT_KEY_LIFE_STEP,
  PERSISTENT_KEY_GAME_CONTINUES_ON_PURPOSE,
  PERSISTENT_KEY_MATCH_START_TIME,

  PERSISTENT_KEY_CONFIG_BASE,
};

void read_persistent_state();
void safe_persistent_state();
